### PR TITLE
Change authentication to apples new SRP6a

### PR DESCRIPTION
**Pull request by PflaeginGmbh**
Hello there,
as mentioned [here](https://github.com/mandarons/icloudpy/issues/48#issuecomment-2428504905), the authentication has changed. This was solved in the origin repository [pyicloud](https://github.com/picklepete/pyicloud/issues/456#issuecomment-2429741020).
These fixes solve the authentication problem and are a slightly modified version of the mentioned solution.

### CODE REVIEW

**Comment by PflaeginGmbh** [comment]
This works for me very well, so i hope that we can finish this task as soon as possible.

**Comment by Eugene-Polonsky** [comment]
I'm getting ('Invalid authentication token.', ICloudPyAPIResponseException('Missing apple_id field')) when trying this.

**Comment by PflaeginGmbh** [comment]
Okay, in the pycloud thread [here](https://github.com/picklepete/pyicloud/issues/456#issuecomment-2434143434)  users experience this your issue too.

First of all, 2FA has to be enabled. In addition [here](https://github.com/picklepete/pyicloud/issues/456#issuecomment-2435751843) is maybe a workaround for enabled 2FA with this error.

**Comment by Eugene-Polonsky** [comment]
Tried all that, still same error. It looks like the code is trying to retrieve a session token, but is providing a null dsWebAuthToken. Hence the error.

**Comment by Eugene-Polonsky** [comment]
This seems to be because session_data does not contain session_token or trust_token. Instead, it contains 'scnt'  and 'client_id' and that's it.

**Comment by Eugene-Polonsky** [comment]
In the original fastlane solution, they reference X-Apple-HC / Challenge headers. I am not seeing that in this solution. Could that be related?

**Comment by Eugene-Polonsky** [comment]
Ok figured it out. Have to use actual password, not app-specific password. Works now.

**Comment by drallgood** [comment]
Can this be merged so the downstream iCloud-docker is fixed too?

**Comment by mandarons** [comment]
It looks like Apple hasn't completely moved to this authentication method yet (e.g. working fine for me without these changes). Is there any way to detect if SRP6a is required for a given apple account? If not, we can have this as a second method if the default (legacy?) authentication fails.

**Review by mandarons — APPROVED** [review]

**Pull request merged**
